import './modules/smooth-scroll.js';
import './modules/map.js';
import './modules/modal.js';
import './modules/validate.js';
import './modules/showmore.js';
import './modules/accordion.js';
import './modules/burger.js';
import './modules/manufacture-slider.js';
import './modules/swiper.js';
